#The Connexion module allows a Python program to use the
#OpenAPI specification with Swagger.
#The Swagger configuration file is a YAML or JSON file
#containing your OpenAPI definitions.

openapi: 3.0.0
#The version string is important because
#some parts of the OpenAPI structure may 
#change over time.

info:
  title: "RP Flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"

servers:
  - url: "/api"
  #you’ll be able to access all of your API paths relative to 
  #http://localhost:8000/api
  
paths:
  #The paths block begins the configuration of the API URL endpoint paths
  /people:
  #The relative URL of your API endpoint
  #Together with the url definition in servers, this creates 
  #the GET /api/people URL endpoint that you can access at
  #http://localhost:8000/api/people

    get: #The HTTP method that this URL endpoint will respond to
      operationId: "people.read_all"
      #The Python function that’ll respond to the request.
      #Connexion will use "people.read_all" to find a Python 
      #function named read_all() in a people module of your project.
      tags:
        - "People"
      summary: "Read the list of people"
      responses:
        "200": #The status codes that the endpoint responds with
          description: "Successfully read people list"